//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.PresentationBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Employees.
        /// </summary>
        internal static string All_Employees {
            get {
                return ResourceManager.GetString("All Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone (not protected).
        /// </summary>
        internal static string Anyone__not_protected_ {
            get {
                return ResourceManager.GetString("Anyone (not protected)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply protection to the document: the file is digitally signed
        ///Please, protect your documents before applying the signature to them.
        /// </summary>
        internal static string CannotProtectDigitallySignedPDF {
            get {
                return ResourceManager.GetString("CannotProtectDigitallySignedPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify and protect.
        /// </summary>
        internal static string Classify_and_protect {
            get {
                return ResourceManager.GetString("Classify and protect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify and protect.
        /// </summary>
        internal static string ClassifyAndProtect {
            get {
                return ResourceManager.GetString("ClassifyAndProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify and protect:.
        /// </summary>
        internal static string ClassifyAndProtectColon {
            get {
                return ResourceManager.GetString("ClassifyAndProtectColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential.
        /// </summary>
        internal static string Confidential {
            get {
                return ResourceManager.GetString("Confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot apply protection document &apos;{documentName}&apos;: the file is opened by another application
        ///Please close the document before applying protection to it.
        /// </summary>
        internal static string DocumentUsedByAnotherProcess {
            get {
                return ResourceManager.GetString("DocumentUsedByAnotherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fsbusitalia.it
        ///GruppoFSItaliane.onmicrosoft.com
        ///ataf.fi.it
        ///bbt-se.com
        ///bluferries.it
        ///c2crail.net
        ///cemat.it
        ///centostazioni.it
        ///crew.it
        ///fercredit.it
        ///ferservizi.it
        ///fondazionefs.it
        ///fs.eu
        ///fsbusitaliacampania.it
        ///fsbusitaliarailservice.it
        ///fsbusitaliasimet.it
        ///fsbusitaliaveneto.it
        ///fseonline.it
        ///fsitaliane.it
        ///fssistemiurbani.it
        ///fstechnology.it
        ///grandistazioni.it
        ///gruppo-fs.it
        ///italcertifer.it
        ///italferr.it
        ///mercitaliaintermodal.it
        ///mercitalialogistics.it
        ///mercitaliarail.it
        ///mercitaliaterminal.it
        ///mercit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Domini {
            get {
                return ResourceManager.GetString("Domini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {count} addresses are not valid.
        /// </summary>
        internal static string EmailAddressesNotValid {
            get {
                return ResourceManager.GetString("EmailAddressesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {address}: is a distribution list and cannot be used as a protection target.
        /// </summary>
        internal static string EmailAddressIsDistributionList {
            get {
                return ResourceManager.GetString("EmailAddressIsDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not an external user.
        /// </summary>
        internal static string EmailAddressNotExternalUser {
            get {
                return ResourceManager.GetString("EmailAddressNotExternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not an internal user.
        /// </summary>
        internal static string EmailAddressNotInternalUser {
            get {
                return ResourceManager.GetString("EmailAddressNotInternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address is not valid.
        /// </summary>
        internal static string EmailAddressNotValid {
            get {
                return ResourceManager.GetString("EmailAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GAL {
            get {
                object obj = ResourceManager.GetObject("GAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highly Confidential.
        /// </summary>
        internal static string Highly_Confidential {
            get {
                return ResourceManager.GetString("Highly Confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-In &apos;{addInDescription}&apos; is loaded
        ///Please unload the &apos;{addInDescription}&apos; Add-In and restart &apos;{applicationName}&apos; to use &apos;Classifica e proteggi&apos;.
        /// </summary>
        internal static string Info_IncompatibleAddIn {
            get {
                return ResourceManager.GetString("Info.IncompatibleAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Login to enter your credentials.
        /// </summary>
        internal static string Info_PressLogin {
            get {
                return ResourceManager.GetString("Info.PressLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal use.
        /// </summary>
        internal static string Internal_use {
            get {
                return ResourceManager.GetString("Internal use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous was incorrect.
        /// </summary>
        internal static string JustificationMessage_PreviousLabelIncorrect {
            get {
                return ResourceManager.GetString("JustificationMessage.PreviousLabelIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous label no longer applies.
        /// </summary>
        internal static string JustificationMessage_PreviousLabelNoLongerApplies {
            get {
                return ResourceManager.GetString("JustificationMessage.PreviousLabelNoLongerApplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document is selected.
        /// </summary>
        internal static string NoDocumentIsSelected {
            get {
                return ResourceManager.GetString("NoDocumentIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No label is available for the document.
        /// </summary>
        internal static string NoLabelAvailableForDocument {
            get {
                return ResourceManager.GetString("NoLabelAvailableForDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file was protected by another account.
        ///Changes to the document classification and protection are reserved to the document owners.
        ///To re-classify or change the protection of the document ask the owner or ask him to enable you to the role of owner..
        /// </summary>
        internal static string NoOwnerDocumentInformation {
            get {
                return ResourceManager.GetString("NoOwnerDocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not an owner for the document =&gt; classification and protection is disabled.
        /// </summary>
        internal static string NoOwnerDocumentInformation2 {
            get {
                return ResourceManager.GetString("NoOwnerDocumentInformation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has been protected from &apos;{ownerAccounts}&apos;.
        ///Access to change sensitivity level or protection
        ///can be required at &apos;{ownerAccounts}&apos; or to contacts shown in &quot;Owners&quot; property for the document.
        /// </summary>
        internal static string NoOwnerDocumentInformation3 {
            get {
                return ResourceManager.GetString("NoOwnerDocumentInformation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To re-classify or change the protection of the document ask the owner or ask him to enable you to the role of owner..
        /// </summary>
        internal static string NoOwnerDocumentInformation5 {
            get {
                return ResourceManager.GetString("NoOwnerDocumentInformation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect document.
        /// </summary>
        internal static string ProtectDocument {
            get {
                return ResourceManager.GetString("ProtectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect document:.
        /// </summary>
        internal static string ProtectDocumentColon {
            get {
                return ResourceManager.GetString("ProtectDocumentColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProtectDocumentIcon {
            get {
                object obj = ResourceManager.GetObject("ProtectDocumentIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients Only.
        /// </summary>
        internal static string Recipients_Only {
            get {
                return ResourceManager.GetString("Recipients Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Protection.
        /// </summary>
        internal static string RemoveProtection {
            get {
                return ResourceManager.GetString("RemoveProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strictly confidential.
        /// </summary>
        internal static string Strictly_confidential {
            get {
                return ResourceManager.GetString("Strictly confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typing....
        /// </summary>
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With footer.
        /// </summary>
        internal static string With_footer {
            get {
                return ResourceManager.GetString("With footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With protection.
        /// </summary>
        internal static string With_protection {
            get {
                return ResourceManager.GetString("With protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without footer.
        /// </summary>
        internal static string Without_footer {
            get {
                return ResourceManager.GetString("Without footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without protection.
        /// </summary>
        internal static string Without_protection {
            get {
                return ResourceManager.GetString("Without protection", resourceCulture);
            }
        }
    }
}
