apiVersion: v1
kind: Service
metadata:
  name: sample-webcli
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: sample-webcli
  type: ClusterIP
